## Set system endpoints
knockknock:
  root: # To be set in runtime

## Logger configuration
logfile:
  # Set log file path (default logfile path: ./knock-knockknock-knock.log) 
  path: ./knock-knock.log
  maxsize: 10
  maxbackups: 3
  maxage: 30
  compress: false

# Set log level, such as trace, debug info, warn, error, fatal, and panic
loglevel: debug

# Set log writer, such as file, stdout, or both
logwriter: both

# Set execution environment, such as development or production
node:
  env: development

## Set internal DB config (SQLlite)
db:
  url: localhost:3306
  database: knock_knock
  user: knock_knock
  password: knock_knock

## Set API access config
api:
  # Set API_ALLOW_ORIGINS (ex: https://A_DOMAIN.org,http://localhost:8080 or * for all)
  allow:
    origins: "*"
  
  # Set API_AUTH_ENABLED=true currently for basic auth for all routes (i.e., url or path)
  auth:
    enabled: true
  
  username: default
  password: default

## Set period for auto control goroutine invocation
autocontrol:
  duration_ms: 10000

## Set SELF_ENDPOINT, to access Swagger API dashboard outside (Ex: export SELF_ENDPOINT=x.x.x.x:8057)
self:
  endpoint: localhost:8057

## Environment variables that you don't need to touch
# Swagger UI API document file path 
apidoc:
  # export APIDOC_PATH=$KNOCKKNOCK_ROOT/pkg/api/rest/docs/swagger.json
  path: # To be set in runtime (based on knockknock.root)
